version: '3.8'

services:

  db:
    extends:
      file: ./services/docker-compose-db.yml
      service: db

  blockscout:
    depends_on:
      - db
    image: blockscout/blockscout:${DOCKER_TAG:-latest}
    pull_policy: always
    restart: always
    stop_grace_period: 5m
    container_name: 'blockscout'
    links:
      - db:database
    command: bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ./envs/common-blockscout.env
    environment:
        ETHEREUM_JSONRPC_VARIANT: 'erigon'
        ETHEREUM_JSONRPC_HTTP_URL: ${ETHEREUM_JSONRPC_HTTP_URL}
        ETHEREUM_JSONRPC_TRACE_URL: ${ETHEREUM_JSONRPC_HTTP_URL}
        ETHEREUM_JSONRPC_WS_URL : ${ETHEREUM_JSONRPC_WS_URL}
        INDEXER_CATCHUP_BLOCKS_BATCH_SIZE : 5
        INDEXER_CATCHUP_BLOCKS_CONCURRENCY : 20
        INDEXER_COIN_BALANCES_BATCH_SIZE : 100
        INDEXER_DISABLE_EMPTY_BLOCKS_SANITIZER : true
        INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER : true
        INDEXER_DISABLE_WITHDRAWALS_FETCHER : false
        INDEXER_INTERNAL_TRANSACTIONS_BATCH_SIZE : 15
        INDEXER_INTERNAL_TRANSACTIONS_CONCURRENCY : 12
        INDEXER_MEMORY_LIMIT : 60
        INDEXER_TOKEN_BALANCES_BATCH_SIZE : 10
        INDEXER_TX_ACTIONS_AAVE_V3_POOL_CONTRACT : 0x87870Bca3F3fD6335C3F4ce8392D69350B4fA4E2
        INDEXER_TX_ACTIONS_ENABLE : true
        INDEXER_TX_ACTIONS_REINDEX_FIRST_BLOCK : 12369621
        INDEXER_TX_ACTIONS_REINDEX_LAST_BLOCK : 17387000
        INDEXER_TX_ACTIONS_UNISWAP_V3_FACTORY_CONTRACT : 0x1F98431c8aD98523631AE4a59f267346ea31F984
        INDEXER_TX_ACTIONS_UNISWAP_V3_NFT_POSITION_MANAGER_CONTRACT : 0xC36442b4a4522E871399CD717aBDD847Ab11FE88
        DATABASE_URL: postgresql://postgres:@host.docker.internal:7432/blockscout?ssl=false
        WITHDRAWALS_FIRST_BLOCK : 17034871
        API_V2_ENABLED : true

        ECTO_USE_SSL: 'false'
        SECRET_KEY_BASE: '56NtB48ear7+wMSf0IQuWDAAazhpb31qyc7GiyspBP2vh7t5zlCsF5QDv76chXeN'
    ports:
      - 4000:4000
    volumes:
      - ./logs/:/app/logs/
